### ISSUE TITLE
Great package! A more thorough description would be nice, though

### ISSUE THREAD

**Issue by emilBeBri** [rpardee/sas#32]
Hi, 

I am so happy you made this! Just the possibility of editing my code in ST3 is a major relief from the terrible built-in editor in SAS.

However, I am a bit confused as to what is possible with this package, beside the code-hightlighting? I mean, I can run a "SAS-build" command and execute a SAS-batch job, but... if I want to see a PROC FREQ, is that possible? And when the batch command is executed, are the work-files deleted afterwards? And is it possible to run only a single line instead of the entire .sas-file?

This would be so helpful if you updated the readme with this information, about the package is capable of. Thank you!

**Comment by popwar2** [comment]
Hello emilBeBri,

Sounds like you've already figured out how to run SAS programs locally from Sublime. You can also configure the build system to call an autoexec prior to running your code, which is great if you multiple macro libraries or projects. As for image/ods output handling and viewing the data, there isn't anything quite as polished as EG, but this package will generate .lst files for all print steps (screen shot example below). 

![2017-05-09_13h58_33](https://cloud.githubusercontent.com/assets/3487129/25865055/a14a6a86-34bf-11e7-940b-4b3b2dac8968.png)

You can also use the ods system to write a file locally (suchs as a png or jpeg of your ouput) and then have it open in sublime. You cannot execute a single line with this editor since its really just pushing the file to your local SAS executable in batch. 

Hope that helps :)

**Comment by rpardee** [comment]
Thanks for the issue--you're right, the readme could be more fleshed out.  Have a look at it now & see what you think.

Some of what you may be attributing to the package is actually just SAS functionality--specifically the ability to batch-submit prewritten sas programs.  That's really all the build system does.  Doing a partial submit like the SAS windowing environment does (e.g., highlight the lines you want to run and having SAS run only those lines) is beyond my meager skills I'm afraid.  See [issue 27](https://github.com/rpardee/sas/issues/27) for details on that.

**Comment by emilBeBri** [comment]
Thank you for the reponse. Yes, the readme is a lot more clear now!

Too bad with the partial submitting of lines from a program! I still enjoy the package immensely, it is so much better than the awfull in-program editor. :)

**Comment by rpardee** [comment]
Excellent--thanks for the response!
